# Generated by Django 6.0.5 on 2026-06-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0005_delete_painelgerencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiroOcupacao',
            fields=[
            ],
            options={
                'verbose_name': '📈 Giro & Ocupação',
                'verbose_name_plural': '📈 Giro & Ocupação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservas.pedidoreserva',),
        ),
    ]
