# Generated by Django 6.0.5 on 2026-06-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
        ('reservas', '0005_delete_painelgerencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnosPico',
            fields=[
            ],
            options={
                'verbose_name': '📈 Turnos de Pico',
                'verbose_name_plural': '📈 Turnos de Picos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservas.pedidoreserva',),
        ),
    ]
