# Generated by Django 6.0.5 on 2026-06-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_turnospico'),
        ('reservas', '0005_delete_painelgerencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaReservas',
            fields=[
            ],
            options={
                'verbose_name': '📈 Frequência de Reservas',
                'verbose_name_plural': '📈 Frequência de Reservas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservas.pedidoreserva',),
        ),
        migrations.AlterModelOptions(
            name='turnospico',
            options={'verbose_name': '📈 Turnos de Pico (Almoço vs. Jantar)', 'verbose_name_plural': '📈 Turnos de Picos (Almoço vs. Jantar)'},
        ),
    ]
