# Generated by Django 6.0.5 on 2026-06-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_frequenciareservas_alter_turnospico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnospico',
            options={'verbose_name': '📈 Almoço vs. Jantar', 'verbose_name_plural': '📈 Almoços vs. Jantares'},
        ),
    ]
