# Generated by Django 6.0.5 on 2026-05-21 16:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail/Usuário')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data do nascimento')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('senha', models.CharField(default='cliente123', max_length=50, verbose_name='Senha de Acesso')),
                ('ativo', models.BooleanField(default=False, verbose_name='Cadastro Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil do Cliente',
                'verbose_name_plural': 'Perfil dos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Identificação da Mesa')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade de Pessoas')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Reserva',
                'verbose_name_plural': 'Tipos de Reserva',
            },
        ),
        migrations.CreateModel(
            name='PedidoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data da Reserva')),
                ('numero_pessoas', models.IntegerField(verbose_name='Nº de Pessoas')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='reservas.cliente', verbose_name='Cliente')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.mesa', verbose_name='Mesa')),
                ('tipo_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.tiporeserva', verbose_name='Tipo da Reserva')),
            ],
            options={
                'verbose_name': 'Pedido de Reserva',
                'verbose_name_plural': 'Pedidos de Reserva',
                'ordering': ['-data'],
            },
        ),
    ]
