# Generated by Django 6.0.5 on 2026-05-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(max_length=20, unique=True, verbose_name='WhatsApp/Usuário'),
        ),
    ]
