# Generated by Django 6.0.5 on 2026-06-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_cliente_email_alter_cliente_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
    ]
