# Generated by Django 6.0.5 on 2026-06-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_cliente_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelGerencial',
            fields=[
            ],
            options={
                'verbose_name': '📊 Painel Gerencial',
                'verbose_name_plural': '📊 Painel Gerencial',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservas.pedidoreserva',),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Cadastro Ativo'),
        ),
    ]
