# Generated by Django 6.0.5 on 2026-06-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_painelgerencial_alter_cliente_ativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PainelGerencial',
        ),
    ]
